MobileTestsAppSolvd/TrainingMobileCycle

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/AddedProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/CartScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/ProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/SuperMarketPanel.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/AddedProductScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/CartScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/ProductScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/SuperMarketBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> RFC03-changingTextLocators

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/PaymentOptionsScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/ProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/ShippingOptionsScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/PaymentOptionsScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/ProductScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/ShippingOptionsScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> TC05_testShippingOptionsScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/SalesScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/SalesScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> TC09-testSalesScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/CellPhoneSalesScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/CellPhoneSalesBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> TC11-testCelPhoneScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/FashionScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/FashionScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> TC12-testFashionScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> RFC-RefactoringFor_Master

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> TC13-testVideosScreen

- src/main/java/binding_TestRail/APIClient.java
- src/main/java/binding_TestRail/APIException.java
- src/main/java/binding_TestRail/TestRailManager.java
- src/main/resources/_config.properties
- src/main/resources/_database.properties
- src/main/resources/_email.properties
- src/main/resources/_testdata.properties
- src/main/resources/agent.properties
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> RFC04-BindingTestRail

- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> RFC05-RefactorTestDescription

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/AddedProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/CartScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/SuperMarketPanel.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/AddedProductScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/CartScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/SuperMarketBase.java
- src/main/resources/_config.properties
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> RFC06-MethodsRename

- src/main/resources/_config.properties
> RFC07-AddConfigurationCapabilities

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> TC14-testVehiclesScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/MoreSoldScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/MoreSoldScreenBase.java
- src/main/resources/_config.properties
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
> TC15-testMoreSoldScreen

- src/test/java/Base/BaseTests.java
> RFC11-AddBaseTestToMaster

- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestCart.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
> RFC08-AddTestSuites

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
> RFC-127-testCelPhoneScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
> RFC-125-testSalesScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/ProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/ProductScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestProducts.java
> RFC124-testBuyNowBtn

- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
> RFC126-testSuperBtn

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
> RFC128-testFashionScreen

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestCart.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestProducts.java
> RFC119-testAddProductToCartBtn

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/ProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/ProductScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestProducts.java
> RFC-123-testKnowMoreScreenOnAProduct

- src/main/java/binding_TestRail/APIClient.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/CartScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/CartScreenBase.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestCart.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
> Create smoke cart test

- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestCart.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
> removeTestFromMaster

- src/main/java/binding_TestRail/APIClient.java
- src/main/java/binding_TestRail/APIException.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/AddedProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/CartScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/CellPhoneSalesScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/FashionScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/HomeScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/KnowMoreScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/MenuCatalog.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/MoreSoldScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/PaymentOptionsScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/ProductScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/SalesScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/SearchPanelBar.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/ShippingOptionsScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/SuperMarketPanel.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/VehiclesScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/android/VideosScreen.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/CartScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/HomeScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/KnowMoreScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/MenuCatalogBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/PaymentOptionsScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/ProductScreenBase.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/common/SuperMarketBase.java
- src/test/java/Base/BaseTests.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestMercadoLibre.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestProducts.java
> RFC12-deleteBlankSpaces

- .idea/.gitignore
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/listener/RecordingListener.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/recorder/RecordingPage.java
- src/test/java/Base/BaseTests.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestCart.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestHome.java
- src/test/java/com/TrainingCycleSolvdArg/carina/demo/TestProducts.java
- src/test/resources/testng_suites/testng_TestHome.xml
> RFC17-addVideoScreenRecorder

- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/listener/RecordingListener.java
- src/main/java/com/TrainingCycleSolvdArg/carina/demo/mobile/gui/recorder/RecordingPage.java
> RFC19-removeCapitalLetters 
